name: dependabump

on:
  schedule:
    - cron: "30 4 * * 0"
  push:
    paths:
      - .github/workflows/versions.yml
      - .github/actions/dependencies/*

jobs:
  apt-get:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Upgrade the dependencies
        uses: ./.github/actions/dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.CARDBOARDCI_PAT_TOKEN }}

      - name: Changes to the environment
        run: |
          git status

      - name: Commit all of the dependencies
        uses: ./.github/actions/auto-commit
        env:
          GITHUB_TOKEN: ${{ secrets.CARDBOARDCI_PAT_TOKEN }}
          BRANCH: '/deps'
          MESSAGE: 'Upgrade packages to latest dependencies'
          PULL_REQUEST_TITLE: 'Bump image dependencies to latest'