name: "git-commit"
description: "Commit changes and raise a pull request."
branding:
  icon: "git-commit"
  color: "green"
inputs:
  title:
    description: "Title of the pull request"
    required: true
  body:
    description: "Body of the pull request"
    required: true
  options:
    description: "Options supplied to the pull request"
    required: true
runs:
  using: "composite"
  steps:
    - id: git-commit
      shell: bash
      run: |
        git commit -m "GitHub Actions commit by ${GITHUB_WORKFLOW}"
        if [ $? -eq 0 ]; then
          git push -u github --force HEAD
          gh pr create --title "${{ inputs.title }}" --body "${{ inputs.body }}" --assign "${{ inputs.username }}" ${{ inputs.options }}
        fi