name: "git-commit"
description: "Commit changes and raise a pull request."
branding:
  icon: "git-commit"
  color: "green"
inputs:
  title:
    description: "Title of the pull request"
    required: true
  body:
    description: "Body of the pull request"
    required: true
  options:
    description: "Options supplied to the pull request"
    required: true
runs:
  using: "composite"
  steps:
    - id: git-commit
      shell: bash
      run: |
        if [[ `git commit -m "GitHub Actions commit by ${GITHUB_WORKFLOW}"` ]]; then
          git push -u github HEAD
          #hub pull-request -m "${{ inputs.title }}" --body "${{ inputs.body }}" ${{ inputs.options }} --assign "${{ inputs.username }}"
        fi