name: 'DockerHub Image Digest'
description: 'Retrieve the image digest associated with a tag.'
inputs:
  url:
    description: 'The docker registry domain'
    required: true
  image:
    description: 'The namespace of the image'
    required: true
  architecture:
    description: 'The architecture of the image'
    required: true
  tag:
    description: 'The tag of the image'
    required: true
outputs:
  image-digest:
    description: "The image digest"
    value: ${{ steps.action.outputs.image-digest }}
runs:
  using: "composite"
  steps:
    - id: action
      shell: bash
      run: |
        request_url="https://${{ inputs.url }}/v2/repositories/${{ inputs.image }}/tags"
        digest=""
        for i in $(seq 1 10); do
            echo "Request: $request_url"
            response=$(wget -q "${request_url}" -O -)
            next_url=`echo $response | jq -r '.next'`

            manifest=`echo $response | jq -r '.results | .[] | select(.name=="${{ inputs.tag }}")'`
            if [[ -n "$manifest" ]]; then
                echo "Found manifest for tag: ${{ inputs.tag }}"
                image=`echo $manifest | jq -r '.images | .[] | select(.architecture=="${{ inputs.architecture }}")'`
                
                echo $image | jq -r "."
                digest=`echo $image | jq -r '.digest'`                
                break;
            fi

            request_url="$next_url"
        done
        echo "::set-output name=image-digest::$digest"
        if [[ -z "$digest" ]]; then
            echo "Failed to find digest for $latest"
            exit 1
        fi