name: 'DockerHub Image Digest'
description: 'Retrieve the image digest associated with a tag.'
inputs:
  url:
    description: 'The docker registry domain'
    required: true
  image:
    description: 'The namespace of the image'
    required: true
  tag:
    description: 'The tag of the image'
    required: true
outputs:
  image-digest:
    description: "The image digest"
    value: ${{ steps.action.outputs.image-digest }}
  image-tag:
    description: "The image tag"
    value: ${{ steps.action.outputs.image-digest }}
runs:
  using: "composite"
  steps:
    - id: action
      shell: bash
      run: |
          request_url="https://${{ inputs.url }}/v2/repositories/${{ inputs.image }}/tags"
          echo "Request: ${request_url}"
          wget -q "${request_url}" -O - | tr -d '[]" ' | tr '}' '\n' | awk -F: '{print $3}' 
          latest=$(wget -q "${request_url}" -O - | tr -d '[]" ' | tr '}' '\n' | awk -F: '{print $3}' | grep '${{ inputs.tag }}' | sort -rn | head -n1)
          echo docker pull ${{ inputs.url }}/${{ inputs.image }}:${latest}
          docker pull ${{ inputs.url }}/${{ inputs.image }}:${latest}
          docker inspect ${{ inputs.url }}/${{ inputs.image }}:${latest}
          image_digest=`docker inspect --format='{{index .RepoDigests 0}}' ${{ inputs.url }}/${{ inputs.image }}:${{ inputs.tag }} | cut -d'@' -f2`
          echo "::set-output name=image-digest::$image_digest"
          echo "::set-output name=image-tag::$latest"