load(":docker-file.bzl", "dockerfile")

dockerfile(
    name = "hugo",
    digest = "sha256:2a0ca344b220f3e922bcca6136f585697573b74bb6f69115a5b152dbfe68bad2",
    vcs_url = "https://gitlab.com/cardboardci/images/hugo",
    summary =  "Hugo static site generator",
    description = " Hugo is an open-source static site generator",
    label_schema = {
        "name" : "hugo",
        "release" : "CardboardCI version:${version} build-date:${build_date}",
        "summary" :"Hugo static site generator",
        "description" : " Hugo is an open-source static site generator",
        "url" : "https://gitlab.com/cardboardci/images/hugo",
        "changelog" : "https://gitlab.com/cardboardci/images/hugo/releases",
        "source_url" : "https://cloud.docker.com/u/cardboardci/repository/docker/cardboardci/hugo",
        "vcs_url" : "https://gitlab.com/cardboardci/images/hugo",
    }
)
