load(":docker-file.bzl", "dockerfile")

dockerfile(
    name = "hugo",
    digest = "sha256:2a0ca344b220f3e922bcca6136f585697573b74bb6f69115a5b152dbfe68bad2",
    vcs_url = "https://github.com/cardboardci/dockerfiles",
    summary =  "Hugo static site generator",
    description = "Hugo is an open-source static site generator",
    version = "0.0.0",
    label_schema = {
        "changelog_url" : "https://github.com/cardboardci/dockerfiles",
    }
)
