name: 'DockerHub Image Digest'
description: 'Retrieve the image digest associated with a tag.'
inputs:
  branch:
    description: 'Temporary'
    required: true
  title:
    description: 'Temporary'
    required: true
  options:
    description: 'Temporary'
    required: true
runs:
  using: "composite"
  steps:
    - id: git-commit
      shell: bash
      run: |
        git checkout -b "${{ inputs.branch }}"
        success=`git commit -m "GitHub Actions commit by ${GITHUB_WORKFLOW}"`
        echo "::set-output name=success::$success"
    - id: pull-request
      shell: bash
      # if: ${{ steps.action.outputs.success }}
      run: |        
        git push -u github HEAD
        #hub pull-request -m "${{ inputs.title }}" ${{ inputs.options }} --assign "${{ inputs.username }}"
