# Project information
site_name: 'CardboardCI'
site_description: 'Temporary website for CardboardCI.'
site_author: 'Jonathan Beverly'
site_dir: public
docs_dir: www

theme:
  name: 'material'
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: 'en'
  palette:
    primary: 'blue'
    accent: 'white'

plugins:
  - search:
      lang: en

extra:
  search:
    lang:
      - en
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/cardboardci'