# Project information
site_name: 'CardboardCI'
site_description: 'Temporary website for CardboardCI.'
site_author: 'Jonathan Beverly'
site_dir: public
docs_dir: www

theme:
  name: 'material'
  # icon: 
  #   logo: assets/icon.png
  favicon: assets/favicon.png
  language: 'en'
  palette:
    primary: 'blue'
    accent: 'white'

# extra:
#   search:
#     lang:
#       - en
#   social:
#     - icon: 'github'
#       link: 'https://github.com/cardboardci'