site_name: "CardboardCI"
site_description: "Website of CardboardCI"
site_author: "Jonathan Beverly"
site_dir: dist
docs_dir: www

theme:
  name: "material"
  logo: assets/icon.png
  favicon: assets/favicon.png
  language: "en"
  palette:
    primary: "blue"
    accent: "white"

plugins:
  - search:
      lang: en

extra:
  search:
    lang:
      - en
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/cardboardci"
