name: awscli-build
on:
  push:
    paths:
      - .github/workflows/awscli.build.yml
      - images/awscli/image_data/**/*
      - images/awscli/test_configs/**/*
      - images/awscli/BUILD

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup bazel
        uses: jwlawson/actions-setup-bazel@v1
        with:
          bazel-version: '3.5.0'

      - name: Set image variables
        id: vars
        run: |
          echo ::set-output name=docker_path::images/awscli
          echo ::set-output name=dockerfile::images/awscli/Dockerfile
          echo ::set-output name=dockerdir::images/awscli/.
          echo ::set-output name=docker_image::ghcr.io/cardboardci/awscli
          echo ::set-output name=docker_tag::$(date -u +'%Y%m%d')

      - name: Build
        run: |
          bazel build //images/awscli:image

      - name: Build
        run: |
          bazel test //images/awscli:tests

      # Configure credentials for container_push in bazel
      - name: Push to GitHub Packages
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.GHCR_PAT  }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          docker push ${{ steps.vars.outputs.docker_image }}