name: awscli-build
on:
  push:
    paths:
      - .github/workflows/awscli.build.yml
      - images/awscli/image_data/**/*
      - images/awscli/test_configs/**/*
      - images/awscli/BUILD

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: |
          bazel build //images/awscli:image

      - name: Test
        run: |
          bazel test //images/awscli:test

      # Configure credentials for container_push in bazel
      - name: Push to GitHub Packages
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.GHCR_PAT  }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          docker push ${{ steps.vars.outputs.docker_image }}