name: build-pdf2htmlex
on:
  push:
    paths:
      - .github/workflows/build.pdf2htmlex.yml
      - .github/actions/image-tag/*
      - images/pdf2htmlex/image_data/**/*
      - images/pdf2htmlex/test_configs/**/*
      - images/pdf2htmlex/BUILD
      - images/base/image_data/**/*
      - images/base/test_configs/**/*
      - images/base/BUILD
      - tests/*.yaml

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: |
          bazel build //images/pdf2htmlex:image

      - name: Test
        run: |
          bazel test //images/pdf2htmlex:test

      - name: Determine tag for image
        id: image
        uses: ./.github/actions/image-tag
        with:
          image: pdf2htmlex
          repository: $GITHUB_REPOSITORY

      - name: Tag Image
        run: |
          bazel run //images/pdf2htmlex:image
          docker tag bazel/images/pdf2htmlex:image ${{ steps.image.outputs.fullname }}
          docker tag bazel/images/pdf2htmlex:image ${{ steps.image.outputs.image }}:edge

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        if: github.ref == 'refs/heads/main'
        run: |
          docker push --all-tags ${{ steps.image.outputs.image}}
