name: build-base
on:
  push:
    paths:
      - .github/workflows/build.base.yml
      - images/base/image_data/**/*
      - images/base/test_configs/**/*
      - images/base/BUILD
      - WORKSPACE
      - tests/*.yaml

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: |
          bazel build //images/base:image

      - name: Test
        run: |
          bazel test //images/base:test

      - name: Set image variables
        id: vars
        run: |
          echo ::set-output name=docker_image::ghcr.io/cardboardci/base
          echo ::set-output name=docker_tag::$(date -u +'%Y%m%d')

      - name: Tag Image
        run: |
          bazel run //images/base:image
          docker tag bazel/images/base:image ${{ steps.vars.outputs.docker_image }}:${{ steps.vars.outputs.docker_tag }}

      - name: Push to GitHub Packages
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.GHCR_PAT  }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          docker push ${{ steps.vars.outputs.docker_image }}