name: build-pylint
on:
  push:
    paths:
      - .github/workflows/build.pylint.yml
      - .github/actions/image-tag/*
      - images/pylint/image_data/**/*
      - images/pylint/test_configs/**/*
      - images/pylint/BUILD
      - WORKSPACE
      - rules/images.bzl
      - images/base/image_data/**/*
      - images/base/test_configs/**/*
      - images/base/BUILD
      - tests/*.yaml

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: |
          bazel build //images/pylint:image

      - name: Test
        run: |
          bazel test //images/pylint:test

      - name: Determine tag for image
        id: image
        uses: ./.github/actions/image-tag
        with:
          image: pylint
          repository: $GITHUB_REPOSITORY

      - name: Tag Image
        run: |
          bazel run //images/pylint:image
          docker tag bazel/images/pylint:image ${{ steps.image.outputs.fullname }}
          docker tag bazel/images/pylint:image ${{ steps.image.outputs.image }}:edge

      - name: Push to GitHub Packages
        if: github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.GHCR_PAT  }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          docker push ${{ steps.image.outputs.image}}
