name: psscriptanalyzer-build
on:
  push:
    paths:
      - .github/workflows/psscriptanalyzer.build.yml
      - images/psscriptanalyzer/image_data/**/*
      - images/psscriptanalyzer/test_configs/**/*
      - images/psscriptanalyzer/BUILD
      - deps/images.bzl

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: |
          bazel build //images/psscriptanalyzer:image

      - name: Test
        run: |
          bazel test //images/psscriptanalyzer:test

      - name: Set image variables
        id: vars
        run: |
          echo ::set-output name=docker_path::images/psscriptanalyzer
          echo ::set-output name=dockerfile::images/psscriptanalyzer/Dockerfile
          echo ::set-output name=dockerdir::images/psscriptanalyzer/.
          echo ::set-output name=docker_image::ghcr.io/cardboardci/psscriptanalyzer
          echo ::set-output name=docker_tag::$(date -u +'%Y%m%d')

      - name: Tag Image
        run: |
          bazel run //images/psscriptanalyzer:image
          docker tag bazel/images/psscriptanalyzer:image ${{ steps.vars.outputs.docker_image }}:${{ steps.vars.outputs.docker_tag }}

      - name: Push to GitHub Packages
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.GHCR_PAT  }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          docker push ${{ steps.vars.outputs.docker_image }}