name: build-gitlab
on:
  push:
    paths:
      - .github/workflows/build.gitlab.yml
      - .github/actions/image-tag/*
      - images/gitlab/image_data/**/*
      - images/gitlab/test_configs/**/*
      - images/gitlab/BUILD
      - WORKSPACE
      - rules/images.bzl
      - images/base/image_data/**/*
      - images/base/test_configs/**/*
      - images/base/BUILD
      - tests/*.yaml

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: |
          bazel build //images/gitlab:image

      - name: Test
        run: |
          bazel test //images/gitlab:test

      - name: Determine tag for image
        id: image
        uses: ./.github/actions/image-tag
        with:
          image: gitlab
          repository: $GITHUB_REPOSITORY

      - name: Tag Image
        run: |
          bazel run //images/gitlab:image
          docker tag bazel/images/gitlab:image ${{ steps.image.outputs.fullname }}
          docker tag bazel/images/gitlab:image ${{ steps.image.outputs.image }}:edge

      - name: Push to GitHub Packages
        if: github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.GHCR_PAT  }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          docker push --all-tags ${{ steps.image.outputs.image}}
