name: dbxcli-build
on:
  push:
    paths:
      - .github/workflows/dbxcli.build.yml
      - images/dbxcli/image_data/**/*
      - images/dbxcli/test_configs/**/*
      - images/dbxcli/BUILD
      - rules/images.bzl

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: |
          bazel build //images/dbxcli:image

      - name: Test
        run: |
          bazel test //images/dbxcli:test

      - name: Set image variables
        id: vars
        run: |
          echo ::set-output name=docker_path::images/dbxcli
          echo ::set-output name=dockerfile::images/dbxcli/Dockerfile
          echo ::set-output name=dockerdir::images/dbxcli/.
          echo ::set-output name=docker_image::ghcr.io/cardboardci/dbxcli
          echo ::set-output name=docker_tag::$(date -u +'%Y%m%d')

      - name: Tag Image
        run: |
          bazel run //images/dbxcli:image
          docker tag bazel/images/dbxcli:image ${{ steps.vars.outputs.docker_image }}:${{ steps.vars.outputs.docker_tag }}

      - name: Push to GitHub Packages
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.GHCR_PAT  }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          docker push ${{ steps.vars.outputs.docker_image }}