name: stylelint-build
on:
  push:
    paths:
      - .github/workflows/build.stylelint.yml
      - images/stylelint/image_data/**/*
      - images/stylelint/test_configs/**/*
      - images/stylelint/BUILD
      - deps/images.bzl

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: |
          bazel build //images/stylelint:image

      - name: Test
        run: |
          bazel test //images/stylelint:test

      - name: Set image variables
        id: vars
        run: |
          echo ::set-output name=docker_path::images/stylelint
          echo ::set-output name=dockerfile::images/stylelint/Dockerfile
          echo ::set-output name=dockerdir::images/stylelint/.
          echo ::set-output name=docker_image::ghcr.io/cardboardci/stylelint
          echo ::set-output name=docker_tag::$(date -u +'%Y%m%d')

      - name: Tag Image
        run: |
          bazel run //images/stylelint:image
          docker tag bazel/images/stylelint:image ${{ steps.vars.outputs.docker_image }}:${{ steps.vars.outputs.docker_tag }}

      - name: Push to GitHub Packages
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.GHCR_PAT  }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          docker push ${{ steps.vars.outputs.docker_image }}