name: build-pdftools
on:
  push:
    paths:
      - .github/workflows/build.pdftools.yml
      - images/pdftools/image_data/**/*
      - images/pdftools/test_configs/**/*
      - images/pdftools/BUILD
      - WORKSPACE
      - images/base/*
      - images/base/**/*
      - tests/*.yaml

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: |
          bazel build //images/pdftools:image

      - name: Test
        run: |
          bazel test //images/pdftools:test

      - name: Set image variables
        id: vars
        run: |
          echo ::set-output name=docker_path::images/pdftools
          echo ::set-output name=dockerfile::images/pdftools/Dockerfile
          echo ::set-output name=dockerdir::images/pdftools/.
          echo ::set-output name=docker_image::ghcr.io/cardboardci/pdftools
          echo ::set-output name=docker_tag::$(date -u +'%Y%m%d')

      - name: Tag Image
        run: |
          bazel run //images/pdftools:image
          docker tag bazel/images/pdftools:image ${{ steps.vars.outputs.docker_image }}:${{ steps.vars.outputs.docker_tag }}

      - name: Push to GitHub Packages
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.GHCR_PAT  }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          docker push ${{ steps.vars.outputs.docker_image }}