name: dependency-imagebase

on:
  schedule:
    - cron: "30 4 * * 4"
  workflow_dispatch:

jobs:
  image-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CARDBOARDCI_PAT_TOKEN }}
      - name: Install buildozer
        run: |
          curl -sSL https://github.com/bazelbuild/buildtools/releases/download/3.5.0/buildozer > buildozer
          chmod +x buildozer
      - name: Find the latest docker tag
        id: tag
        uses: ./.github/actions/docker-image-tag
        with:
          url: registry.hub.docker.com
          image: library/ubuntu
          query: focal-
      - name: Get the docker image sha
        id: digest
        uses: ./.github/actions/docker-image-digest
        with:
          url: registry.hub.docker.com
          image: library/ubuntu
          architecture: amd64
          tag: ${{ steps.tag.outputs.image-tag }}
      - name: Determine the current image digest
        id: source
        run: |
          image_digest=`cat WORKSPACE | ./buildozer 'print digest' -:ubuntu`
          echo "::set-output name=image-digest::$image_digest"
      - name: Print the determined image digests
        run: |
          echo DockerHub digest ${{ steps.digest.outputs.image-digest }}
          echo Source digest ${{ steps.source.outputs.image-digest }}
      - name: Configure git
        if: ${{ steps.digest.outputs.image-digest != steps.source.outputs.image-digest }}
        uses: ./.github/actions/git-config
        with:
          username: jrbeverly
          email: jonathan@jrbeverly.me
          branch: "base-image-to-${{ steps.tag.outputs.image-tag }}"
          token: ${{ secrets.CARDBOARDCI_PAT_TOKEN }}
      - name: Buildozer to edit digest
        if: ${{ steps.digest.outputs.image-digest != steps.source.outputs.image-digest }}
        run: |
          set -x
          cat WORKSPACE | ./buildozer 'set digest "${{ steps.digest.outputs.image-digest }}"' "-:ubuntu" | tee WORKSPACE.tmp
          rm WORKSPACE
          mv WORKSPACE.tmp WORKSPACE
          git add -f WORKSPACE
      - name: Commit all of the dependencies
        uses: ./.github/actions/git-commit
        if: ${{ steps.digest.outputs.image-digest != steps.source.outputs.image-digest && github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.CARDBOARDCI_PAT_TOKEN }}
        with:
          username: jrbeverly
          title: "Bump base image to ${{ steps.tag.outputs.image-tag }} tag"
          body: "Bumps the base image to `${{ steps.tag.outputs.image-tag }}`.\n\nReplaces the old ubuntu image digest with the latest digest for tag `${{ steps.dockerhub.outputs.image-tag }}`.\n - source-digest: `${{ steps.source.outputs.image-digest }}`\n - tag-digest: `${{ steps.dockerhub.outputs.image-digest }}`"
          options: "--label dependencies"
