name: dependency-imagebase

on:
  schedule:
    - cron: "30 4 * * 4"
  workflow_dispatch:

jobs:
  image-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CARDBOARDCI_PAT_TOKEN }}
      - name: Test remotes
        run: |
          git remote -v
      - name: Install buildozer
        run: |
          curl -sSL https://github.com/bazelbuild/buildtools/releases/download/3.5.0/buildozer > buildozer
          curl -sSL https://github.com/bazelbuild/buildtools/releases/download/3.5.0/buildifier > buildifier
          chmod +x buildozer
          chmod +x buildifier
      - name: Get the docker image sha
        id: dockerhub
        uses: ./.github/actions/docker-image-digest
        with:
          url: registry.hub.docker.com
          image: library/ubuntu
          tag: focal-
      - name: Determine the current image digest
        id: source
        run: |
          image_digest=`cat WORKSPACE | ./buildozer 'print digest' -:ubuntu`
          echo "::set-output name=image-digest::$image_digest"
      - name: Print the determined image digests
        run: |
          echo DockerHub digest ${{ steps.dockerhub.outputs.image-digest }}
          echo Source digest ${{ steps.source.outputs.image-digest }}
      - name: Configure git
        if: ${{ steps.dockerhub.outputs.image-digest != steps.source.outputs.image-digest }}
        uses: ./.github/actions/git-config
        with:
          username: jrbeverly
          email: jonathan@jrbeverly.me
          branch: 'base-image-to-${{ steps.dockerhub.outputs.image-tag }}'
          token: ${{ secrets.CARDBOARDCI_PAT_TOKEN }}
      - name: Buildozer to edit digest
        # if: ${{ steps.dockerhub.outputs.image-digest != steps.source.outputs.image-digest }}
        run: |
          set -x
          cat WORKSPACE | ./buildozer 'set digest "${{ steps.dockerhub.outputs.image-digest }}"' "-:ubuntu" | tee WORKSPACE.tmp
          rm WORKSPACE
          mv WORKSPACE.tmp WORKSPACE
          git add -f WORKSPACE
      # - name: Commit all of the dependencies
      #   uses: ./.github/actions/git-commit
      #   # if: ${{ steps.dockerhub.outputs.image-digest != steps.source.outputs.image-digest && github.ref == 'refs/heads/master' }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.CARDBOARDCI_PAT_TOKEN }}
      #   with:
      #     options: "--label dependencies"
      #     body: "Bumps the base image to `${{ steps.dockerhub.outputs.image-tag }}`.\n\nReplaces the old ubuntu image digest with the latest digest for tag `${{ steps.dockerhub.outputs.image-tag }}`.\n - source-digest: `${{ steps.source.outputs.image-digest }}`\n - tag-digest: `${{ steps.dockerhub.outputs.image-digest }}`"
      #     title: "Bump base image to ${{ steps.dockerhub.outputs.image-tag }} tag"
