name: dependecy-imagebase

on:
  schedule:
    - cron: "30 4 6 * *"
  push:
    paths:
      - .github/workflows/upgrader.base.yml
      - .github/actions/docker-hub-image-digest/*

jobs:
  apt-get:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install buildozer
        run: |
          curl -sSL https://github.com/bazelbuild/buildtools/releases/download/3.5.0/buildozer > /usr/local/bin/buildozer
          chmod +x /usr/local/bin/buildozer
      - name: Get the dockerhub image sha
        id: dockerhub
        uses: ./.github/actions/docker-hub-image-digest
        with:
          url: registry.hub.docker.com
          image: library/ubuntu
          arch: amd64
          tag: focal
      - name: Determine the current image digest
        id: source
        run: |
          image_digest=`cat WORKSPACE | buildozer 'print digest' -:ubuntu`
          echo "::set-output name=image-digest::$image_digest"
      - name: Changes to the environment
        run: |
          echo DockerHub digest ${{ steps.dockerhub.outputs.image-digest }}
          echo Source digest ${{ steps.source.outputs.image-digest }}
      #     git status
      # - name: Commit all of the dependencies
      #   uses: ./.github/actions/auto-commit
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.CARDBOARDCI_PAT_TOKEN }}
      #     BRANCH: '/deps'
      #     MESSAGE: 'Upgrade packages to latest dependencies'
      #     PULL_REQUEST_TITLE: 'Bump image dependencies to latest'