name: dependecy-imagebase

on:
  schedule:
    - cron: "30 4 6 * *"
  push:
    paths:
      - .github/workflows/upgrader.base.yml
      - .github/actions/docker-hub-image-digest/*

jobs:
  apt-get:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # - name: Get latest dockerhub image sha
      #   uses: ./.github/actions/docker-hub-image-digest
      #   env:
      #     REGISTRY_URL: registry.hub.docker.com
      #     REGISTRY_IMAGE: library/ubuntu
      #     REGISTRY_ARCH: amd64
      #     REGISTRY_TAG: focal
      - name: Get the dockerhub image sha
        id: dockerhub
        uses: ./.github/actions/docker-hub-image-digest
        with:
          url: registry.hub.docker.com
          image: library/ubuntu
          arch: amd64
          tag: focal
      - run: echo random-number ${{ steps.dockerhub.outputs.image-digest }}
        shell: bash