name: dependabump

on:
  # schedule:
  # - cron: "30 4 * * *"
  push:
    paths:
      - .github/workflows/versions.yml
      - .github/actions/dependencies/*

jobs:
  apt-get:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Upgrade the dependencies
        uses: ./.github/actions/dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}