name: "Build and Deploy"
on:
  push:
    paths:
      - .github/workflows/website.yml
      - docs/*
      - docs/**/*
      - images/**/*.md

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy to docs directory
        working-directory: images/
        run: |
          for x in *; do cp ${x}/README.md ${GITHUB_WORKSPACE}/docs/www/images/${x}.md ; done
      - name: Copy to docs directory
        run: |
          bazel build //docs:website
      - name: Copy to docs directory
        run: |
          cp bazel-bin/docs/website/website.tar .
          tar -xf website.tar
          ls public/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public