name: wkhtmltopdf-hub
on:
  push:
    branches:
      - master
    paths:
    - definitions/wkhtmltopdf/README.md
    - .github/workflows/wkhtmltopdf.hub.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: cardboardci/wkhtmltopdf
          README_FILEPATH: definitions/wkhtmltopdf/README.md