name: 'DockerHub Image Tag'
description: 'Retrieve the latest tag matching the query. Latest is determined by tag ordering.'
inputs:
  url:
    description: 'The docker registry domain'
    required: true
  image:
    description: 'The namespace of the image'
    required: true
  query:
    description: 'The search term for the image tag'
    required: true
outputs:
  image-tag:
    description: "The image tag"
    value: ${{ steps.action.outputs.image-tag }}
runs:
  using: "composite"
  steps:
    - id: action
      shell: bash
      run: |
          request_url="https://${{ inputs.url }}/v1/repositories/${{ inputs.image }}/tags"
          echo "Request: ${request_url}"
          latest=$(wget -q "${request_url}" -O - | tr -d '[]" ' | tr '}' '\n' | awk -F: '{print $3}' | grep 'focal-' | sort -rn | head -n1)
          echo "::set-output name=image-tag::$latest"